### ISSUE TITLE
Need emit event of 'lostFocus' on lostfocus

### ISSUE THREAD

**Issue by durgeshahire4** [miroshko/vanilla-color-picker#3]
Description;

Need to add `.emit('lostFocus');`

**Comment by durgeshahire4** [comment]
@miroshko can you Please look into this issue. I have send PR for it. #4

**Comment by miroshko** [comment]
closed by 1423b2db8b5e39bc35b3b04a37b08c9c95f0dfde

**Comment by durgeshahire4** [comment]
@miroshko thanks
